### ISSUE TITLE
Fischer time control

### ISSUE THREAD

**Issue by SzotsGabor** [mikeleany/tinman#11] opened 2020-02-02 07:54 UTC
It seems the engine can't play with x base + y increment TC. It made 1 move then no more.

**Comment by mikeleany** [comment] 2020-02-02 19:58
Thank you for making me aware of your issue. I haven't been able to reproduce it. If you're able to find, and post the log file that would be very helpful. It would be named "tinman.log", and may be located in your home directory, or a directory where the engine was run from.

Also, it would be helpful if you could answer the following questions:
 - What operating system are you using?
 - What user interface are you using?
 - What is the specific time control setting?
 - Was the executable compiled on the system you are running it on, or did you download a compile someone else made, or perhaps compile it on another system and then copy it over?

Thanks.

**Comment by SzotsGabor** [comment] 2020-02-03 07:18
Hello Mike,

Oddly, I myself cannot reproduce the error, I don't know what happened. Apologies for the false alarm.
Anyway, here are answers to your questions:
I use 64-bit Win10 Home Edition.
I use the Arena GUI, version 3.5.1.
TC was 2m+1s.
I used the compile Tony Mokonen made from your 0.1.1 sources.

Gabor Szots
CCRL testing group

**Comment by mikeleany** [comment] 2020-02-03 15:13
Thank you. If it happened once, it will probably happen again sometime, but is probably intermittent and might be unrelated to time controls. If you do see it again, it would be great if you could provide me with the log. Hopefully with the log I would be able to reproduce it more easily and hopefully find and fix the cause of the issue.

Thanks.

**Comment by mikeleany** [comment] 2020-06-07 02:01
Closing this issue, as I have not been able to reproduce it, nor heard of any further occurrences. If it happens again, feel free to re-open this issue.

**Closed by mikeleany** 2020-06-07 02:01 UTC
Labels: works for me
